2020-04-20 23:14:58,717 : CRITICAL : IndexError occurred
Traceback (most recent call last):
  File "d:/Archivos/Programacion-1/UF3/projecte1/main.py", line 60, in <module>
    lista1 = row[1]
IndexError: list index out of range
2020-04-22 16:54:55,700 : CRITICAL : TypeError occurred
Traceback (most recent call last):
  File "d:/Archivos/Programacion-1/UF3/projecte1/main.py", line 54, in <module>
    lista = row[row]
TypeError: list indices must be integers, not list
